ETL into pdap/data-intake
Police-Data-Accessibility-Project/PDAP-Scrapers pull request #113
Opened 2021-05-25 18:02 UTC by EricTurner3

ETL Package refactored to read from `schema.json` file and will now:
- search for `agency_id` and grab the record
- search for all available `dataset_id`, insert if they do not exist
- search for `data_type`, verify it exists, then grab the same named table in `pdap/data-intake`
- sync the `mapping` in `schema.json` to match the columns for the `pdap/data-intake` table
- output all the modifications (sync) back out to the `schema.json` file

Still work-in-progress:
- use the synced `mapping` from the database to actually enumerate the scraped data records and ingest them into `pdap/data-intake`

2021-05-25 21:21 UTC, EricTurner3 commented
Successfully loaded data into DoltHub!

- [pdap/data-intake](https://www.dolthub.com/repositories/pdap/data-intake/pulls/7) (all the data in the bulletins tables are from this etl process)
- [pdap/datasets](https://www.dolthub.com/repositories/pdap/datasets/pulls/39/compare) (two new datasets for the agency)

2021-05-26 14:38 UTC, CaptainStabs commented on USA/CA/butte_county/college/chico/data/daily_bulletins/CSUCPD_2021_05_19_daily_bulletin
> +13,Outside Warrant Arrest FELONY     Cntl Sub Paraphernalia,21-0216,5/8/2021 21:45,5/8/2021  21:45 - 5/8/2021 23:02,"Mansion Av/Arcadian Av, Chico",Crime Cleared by Arrest 5/8/2021
May want to truncate the data.

2021-05-26 14:46 UTC, CaptainStabs requested changes
Add the newline to the commented files and it should be good to go. 

https://gcc.gnu.org/legacy-ml/gcc/2003-11/msg01568.html

2021-05-26 14:46 UTC, CaptainStabs commented on USA/CA/butte_county/college/chico/etl.py
> +    json.dump(schema, outfile, indent=4)
Newline missing

2021-05-26 14:46 UTC, CaptainStabs commented on USA/CA/butte_county/college/chico/etl.py
> +    json.dump(schema, outfile, indent=4)
Add newline at end of file

2021-05-26 14:46 UTC, CaptainStabs commented on USA/CA/butte_county/college/chico/main.py
> +import etl
Add newline

2021-05-26 14:46 UTC, CaptainStabs commented on USA/CA/butte_county/college/chico/schema.json
>  }
add newline

2021-05-26 14:46 UTC, CaptainStabs commented on common/etl/main.py
> +    return schema
add newline

2021-05-26 14:46 UTC, CaptainStabs commented on common/etl/pdap_dolt.py
>          print(  '[!] ERROR: Cannot push to main branch. Aborting. Use dolt cli to migrate and finalize commit')
Add newline

2021-05-26 14:54 UTC, EricTurner3 commented
I updated my settings to Insert NewLines and will do PEP8 formatting and unit tests in the next PR. I just do not want to increase this PR as it functionally is working fine and our pipeline does not currently have specific formatting requirements.

2021-05-26 14:57 UTC, CaptainStabs approved these changes
Other than the formatting (which he will fix in a different PR), the code looks good.

2021-05-26 15:02 UTC, merged